//  swiftlint:disable all
//
//  The code generated using FigmaExport — Command line utility to export
//  colors, typography, icons and images from Figma to Xcode project.
//
//  https://github.com/RedMadRobot/figma-export
//
//  Don’t edit this code manually to avoid runtime crashes
//

import SwiftUI

private class BundleProvider {
    static let bundle = Bundle(for: BundleProvider.self)
}

public extension Image {
    static var ic12ArrowDown: Image { Image(#function) }
    static var ic12ArrowUp: Image { Image(#function) }
    static var ic12Clock: Image { Image(#function) }
    static var ic12Close: Image { Image(#function) }
    static var ic12Coins: Image { Image(#function) }
    static var ic12EyeOff: Image { Image(#function) }
    static var ic12Lock: Image { Image(#function) }
    static var ic12Lockandeyeoff: Image { Image(#function) }
    static var ic12LogoForaColor: Image { Image(#function) }
    static var ic12Navigation: Image { Image(#function) }
    static var ic12Percent: Image { Image(#function) }
    static var ic12Shield: Image { Image(#function) }
    static var ic12Star: Image { Image(#function) }
    static var ic12Zap: Image { Image(#function) }
    static var ic16Ball: Image { Image(#function) }
    static var ic1612Circle: Image { Image(#function) }
    static var ic16Tariff: Image { Image(#function) }
    static var ic16Zkx: Image { Image(#function) }
    static var ic16Activity: Image { Image(#function) }
    static var ic16AdditionalCardGrey: Image { Image(#function) }
    static var ic16AdditionalCardWhite: Image { Image(#function) }
    static var ic16Airplay: Image { Image(#function) }
    static var ic16AlertCircle: Image { Image(#function) }
    static var ic16AlertOctagon: Image { Image(#function) }
    static var ic16AlertTriangle: Image { Image(#function) }
    static var ic16AlignCenter: Image { Image(#function) }
    static var ic16AlignJustify: Image { Image(#function) }
    static var ic16AlignLeft: Image { Image(#function) }
    static var ic16AlignRight: Image { Image(#function) }
    static var ic16Anchor: Image { Image(#function) }
    static var ic16Aperture: Image { Image(#function) }
    static var ic16Apple: Image { Image(#function) }
    static var ic16Archive: Image { Image(#function) }
    static var ic16ArrowDown: Image { Image(#function) }
    static var ic16ArrowDownCircle: Image { Image(#function) }
    static var ic16ArrowDownLeft: Image { Image(#function) }
    static var ic16ArrowDownLine: Image { Image(#function) }
    static var ic16ArrowDownRight: Image { Image(#function) }
    static var ic16ArrowLeft: Image { Image(#function) }
    static var ic16ArrowLeftCircle: Image { Image(#function) }
    static var ic16ArrowRight: Image { Image(#function) }
    static var ic16ArrowRightCircle: Image { Image(#function) }
    static var ic16ArrowUp: Image { Image(#function) }
    static var ic16ArrowUpCircle: Image { Image(#function) }
    static var ic16ArrowUpLeft: Image { Image(#function) }
    static var ic16ArrowUpRight: Image { Image(#function) }
    static var ic16AtSign: Image { Image(#function) }
    static var ic16Award: Image { Image(#function) }
    static var ic16Bank: Image { Image(#function) }
    static var ic16BarChart: Image { Image(#function) }
    static var ic16BarChart2: Image { Image(#function) }
    static var ic16BarInOrder: Image { Image(#function) }
    static var ic16BarcodeScanner2: Image { Image(#function) }
    static var ic16Battery: Image { Image(#function) }
    static var ic16BatteryCharging: Image { Image(#function) }
    static var ic16Bell: Image { Image(#function) }
    static var ic16BellOff: Image { Image(#function) }
    static var ic16BirthdayCake: Image { Image(#function) }
    static var ic16Bluetooth: Image { Image(#function) }
    static var ic16Bold: Image { Image(#function) }
    static var ic16Book: Image { Image(#function) }
    static var ic16BookOpen: Image { Image(#function) }
    static var ic16Bookmark: Image { Image(#function) }
    static var ic16Box: Image { Image(#function) }
    static var ic16Briefcase: Image { Image(#function) }
    static var ic16Cafe: Image { Image(#function) }
    static var ic16Calendar: Image { Image(#function) }
    static var ic16CalendarPayment: Image { Image(#function) }
    static var ic16Camera: Image { Image(#function) }
    static var ic16CameraOff: Image { Image(#function) }
    static var ic16Cash: Image { Image(#function) }
    static var ic16Cashback: Image { Image(#function) }
    static var ic16Cashterminal: Image { Image(#function) }
    static var ic16Cast: Image { Image(#function) }
    static var ic16Check: Image { Image(#function) }
    static var ic16CheckCircle: Image { Image(#function) }
    static var ic16CheckSquare: Image { Image(#function) }
    static var ic16ChevronDown: Image { Image(#function) }
    static var ic16ChevronLeft: Image { Image(#function) }
    static var ic16ChevronRight: Image { Image(#function) }
    static var ic16ChevronUp: Image { Image(#function) }
    static var ic16ChevronsDown: Image { Image(#function) }
    static var ic16ChevronsLeft: Image { Image(#function) }
    static var ic16ChevronsRight: Image { Image(#function) }
    static var ic16ChevronsUp: Image { Image(#function) }
    static var ic16Chrome: Image { Image(#function) }
    static var ic16Circle: Image { Image(#function) }
    static var ic16CircleClose: Image { Image(#function) }
    static var ic16CircleRefresh: Image { Image(#function) }
    static var ic16Clipboard: Image { Image(#function) }
    static var ic16Clock: Image { Image(#function) }
    static var ic16Close: Image { Image(#function) }
    static var ic16Clothes: Image { Image(#function) }
    static var ic16Cloud: Image { Image(#function) }
    static var ic16CloudDrizzle: Image { Image(#function) }
    static var ic16CloudLightning: Image { Image(#function) }
    static var ic16CloudOff: Image { Image(#function) }
    static var ic16CloudRain: Image { Image(#function) }
    static var ic16CloudSnow: Image { Image(#function) }
    static var ic16Code: Image { Image(#function) }
    static var ic16Codepen: Image { Image(#function) }
    static var ic16Codesandbox: Image { Image(#function) }
    static var ic16Coffee: Image { Image(#function) }
    static var ic16Coins: Image { Image(#function) }
    static var ic16Columns: Image { Image(#function) }
    static var ic16Command: Image { Image(#function) }
    static var ic16Compass: Image { Image(#function) }
    static var ic16Copy: Image { Image(#function) }
    static var ic16CornerDownLeft: Image { Image(#function) }
    static var ic16CornerDownRight: Image { Image(#function) }
    static var ic16CornerLeftDown: Image { Image(#function) }
    static var ic16CornerLeftUp: Image { Image(#function) }
    static var ic16CornerRightDown: Image { Image(#function) }
    static var ic16CornerRightUp: Image { Image(#function) }
    static var ic16CornerUpLeft: Image { Image(#function) }
    static var ic16CornerUpRight: Image { Image(#function) }
    static var ic16Cpu: Image { Image(#function) }
    static var ic16CreditCard: Image { Image(#function) }
    static var ic16CreditCardValidity: Image { Image(#function) }
    static var ic16Crop: Image { Image(#function) }
    static var ic16Crosshair: Image { Image(#function) }
    static var ic16Crosshair1: Image { Image(#function) }
    static var ic16Customer: Image { Image(#function) }
    static var ic16Database: Image { Image(#function) }
    static var ic16DeactivatedCreditCard: Image { Image(#function) }
    static var ic16Delete: Image { Image(#function) }
    static var ic16Denied: Image { Image(#function) }
    static var ic16Disc: Image { Image(#function) }
    static var ic16Divide: Image { Image(#function) }
    static var ic16DivideCircle: Image { Image(#function) }
    static var ic16DivideSquare: Image { Image(#function) }
    static var ic16DollarSign: Image { Image(#function) }
    static var ic16Download: Image { Image(#function) }
    static var ic16DownloadCloud: Image { Image(#function) }
    static var ic16Dribbble: Image { Image(#function) }
    static var ic16Droplet: Image { Image(#function) }
    static var ic16Edit: Image { Image(#function) }
    static var ic16Edit2: Image { Image(#function) }
    static var ic16Edit3: Image { Image(#function) }
    static var ic16Education: Image { Image(#function) }
    static var ic16Egrn: Image { Image(#function) }
    static var ic16ExternalLink: Image { Image(#function) }
    static var ic16Eye: Image { Image(#function) }
    static var ic16EyeOff: Image { Image(#function) }
    static var ic16Facebook: Image { Image(#function) }
    static var ic16FastForward: Image { Image(#function) }
    static var ic16Favorites: Image { Image(#function) }
    static var ic16Feather: Image { Image(#function) }
    static var ic16Figma: Image { Image(#function) }
    static var ic16File: Image { Image(#function) }
    static var ic16FileHash: Image { Image(#function) }
    static var ic16FileMinus: Image { Image(#function) }
    static var ic16FilePlus: Image { Image(#function) }
    static var ic16FileText: Image { Image(#function) }
    static var ic16Film: Image { Image(#function) }
    static var ic16Filter: Image { Image(#function) }
    static var ic16Flag: Image { Image(#function) }
    static var ic16Folder: Image { Image(#function) }
    static var ic16FolderMinus: Image { Image(#function) }
    static var ic16FolderPlus: Image { Image(#function) }
    static var ic16Framer: Image { Image(#function) }
    static var ic16Frown: Image { Image(#function) }
    static var ic16Gamepad: Image { Image(#function) }
    static var ic16Gift: Image { Image(#function) }
    static var ic16GitBranch: Image { Image(#function) }
    static var ic16GitCommit: Image { Image(#function) }
    static var ic16GitMerge: Image { Image(#function) }
    static var ic16GitPullRequest: Image { Image(#function) }
    static var ic16Github: Image { Image(#function) }
    static var ic16Gitlab: Image { Image(#function) }
    static var ic16Globe: Image { Image(#function) }
    static var ic16Grid: Image { Image(#function) }
    static var ic16HardDrive: Image { Image(#function) }
    static var ic16Hash: Image { Image(#function) }
    static var ic16Headphones: Image { Image(#function) }
    static var ic16Heart: Image { Image(#function) }
    static var ic16Heartbeat: Image { Image(#function) }
    static var ic16HelpCircle: Image { Image(#function) }
    static var ic16Hexagon: Image { Image(#function) }
    static var ic16Holiday: Image { Image(#function) }
    static var ic16Home: Image { Image(#function) }
    static var ic16IconMessage: Image { Image(#function) }
    static var ic16Image: Image { Image(#function) }
    static var ic16Inbox: Image { Image(#function) }
    static var ic16Info: Image { Image(#function) }
    static var ic16Instagram: Image { Image(#function) }
    static var ic16Italic: Image { Image(#function) }
    static var ic16Key: Image { Image(#function) }
    static var ic16Layers: Image { Image(#function) }
    static var ic16Layout: Image { Image(#function) }
    static var ic16LifeBuoy: Image { Image(#function) }
    static var ic16Limits: Image { Image(#function) }
    static var ic16Link: Image { Image(#function) }
    static var ic16Link2: Image { Image(#function) }
    static var ic16Linkedin: Image { Image(#function) }
    static var ic16List: Image { Image(#function) }
    static var ic16Loader: Image { Image(#function) }
    static var ic16Location: Image { Image(#function) }
    static var ic16Lock: Image { Image(#function) }
    static var ic16LogIn: Image { Image(#function) }
    static var ic16LogOut: Image { Image(#function) }
    static var ic16LogoForaOneColor: Image { Image(#function) }
    static var ic16Mail: Image { Image(#function) }
    static var ic16MainCardGrey: Image { Image(#function) }
    static var ic16MainCardGreyFixed2: Image { Image(#function) }
    static var ic16MainCardWhite: Image { Image(#function) }
    static var ic16MainCardWhiteFixed2: Image { Image(#function) }
    static var ic16Map: Image { Image(#function) }
    static var ic16MapPin: Image { Image(#function) }
    static var ic16MathMinus: Image { Image(#function) }
    static var ic16MathPlus: Image { Image(#function) }
    static var ic16Maximize: Image { Image(#function) }
    static var ic16MaximizeHorizontal: Image { Image(#function) }
    static var ic16MaximizeArrow: Image { Image(#function) }
    static var ic16MaximizeSquare: Image { Image(#function) }
    static var ic16Meh: Image { Image(#function) }
    static var ic16Menu: Image { Image(#function) }
    static var ic16MessageCircle: Image { Image(#function) }
    static var ic16MessageSquare: Image { Image(#function) }
    static var ic16Metro: Image { Image(#function) }
    static var ic16Mic: Image { Image(#function) }
    static var ic16MicOff: Image { Image(#function) }
    static var ic16Minimize: Image { Image(#function) }
    static var ic16Minimize2: Image { Image(#function) }
    static var ic16MinusCircle: Image { Image(#function) }
    static var ic16MinusSquare: Image { Image(#function) }
    static var ic16MinusSquares: Image { Image(#function) }
    static var ic16Monitor: Image { Image(#function) }
    static var ic16Moon: Image { Image(#function) }
    static var ic16MoreHorizontal: Image { Image(#function) }
    static var ic16MoreVertical: Image { Image(#function) }
    static var ic16MousePointer: Image { Image(#function) }
    static var ic16Move: Image { Image(#function) }
    static var ic16Music: Image { Image(#function) }
    static var ic16Navigation: Image { Image(#function) }
    static var ic16Octagon: Image { Image(#function) }
    static var ic16Package: Image { Image(#function) }
    static var ic16Paperclip: Image { Image(#function) }
    static var ic16Pass: Image { Image(#function) }
    static var ic16Pause: Image { Image(#function) }
    static var ic16PauseCircle: Image { Image(#function) }
    static var ic16PaymentMethod: Image { Image(#function) }
    static var ic16PenTool: Image { Image(#function) }
    static var ic16Percent: Image { Image(#function) }
    static var ic16PercentCommission: Image { Image(#function) }
    static var ic16Permissions: Image { Image(#function) }
    static var ic16Phone: Image { Image(#function) }
    static var ic16PhoneCall: Image { Image(#function) }
    static var ic16PhoneForwarded: Image { Image(#function) }
    static var ic16PhoneIncoming: Image { Image(#function) }
    static var ic16PhoneMissed: Image { Image(#function) }
    static var ic16PhoneOff: Image { Image(#function) }
    static var ic16PhoneOutgoing: Image { Image(#function) }
    static var ic16PieChart: Image { Image(#function) }
    static var ic16Pincode: Image { Image(#function) }
    static var ic16Plane: Image { Image(#function) }
    static var ic16Play: Image { Image(#function) }
    static var ic16PlayCircle: Image { Image(#function) }
    static var ic16Plus: Image { Image(#function) }
    static var ic16PlusCircle: Image { Image(#function) }
    static var ic16PlusSquare: Image { Image(#function) }
    static var ic16PlusSquares: Image { Image(#function) }
    static var ic16Pocket: Image { Image(#function) }
    static var ic16PoligonDown: Image { Image(#function) }
    static var ic16PoligonUp: Image { Image(#function) }
    static var ic16Power: Image { Image(#function) }
    static var ic16Printer: Image { Image(#function) }
    static var ic16Promotions: Image { Image(#function) }
    static var ic16Radio: Image { Image(#function) }
    static var ic16RefreshCcw: Image { Image(#function) }
    static var ic16RefreshCw: Image { Image(#function) }
    static var ic16Repeat: Image { Image(#function) }
    static var ic16ResendCard: Image { Image(#function) }
    static var ic16Rewind: Image { Image(#function) }
    static var ic16Roller: Image { Image(#function) }
    static var ic16RotateCcw: Image { Image(#function) }
    static var ic16RotateCw: Image { Image(#function) }
    static var ic16Rss: Image { Image(#function) }
    static var ic16Save: Image { Image(#function) }
    static var ic16ScanCard: Image { Image(#function) }
    static var ic16Scissors: Image { Image(#function) }
    static var ic16Search: Image { Image(#function) }
    static var ic16Send: Image { Image(#function) }
    static var ic16Server: Image { Image(#function) }
    static var ic16Settings: Image { Image(#function) }
    static var ic16Share: Image { Image(#function) }
    static var ic16Share2: Image { Image(#function) }
    static var ic16Shield: Image { Image(#function) }
    static var ic16ShieldOff: Image { Image(#function) }
    static var ic16ShoppingBag: Image { Image(#function) }
    static var ic16ShoppingCart: Image { Image(#function) }
    static var ic16Shuffle: Image { Image(#function) }
    static var ic16Sidebar: Image { Image(#function) }
    static var ic16SkanCard: Image { Image(#function) }
    static var ic16SkipBack: Image { Image(#function) }
    static var ic16SkipForward: Image { Image(#function) }
    static var ic16Slack: Image { Image(#function) }
    static var ic16Slash: Image { Image(#function) }
    static var ic16Sliders: Image { Image(#function) }
    static var ic16Smartphone: Image { Image(#function) }
    static var ic16Smile: Image { Image(#function) }
    static var ic16SmsCode: Image { Image(#function) }
    static var ic16Speaker: Image { Image(#function) }
    static var ic16Square: Image { Image(#function) }
    static var ic16Star: Image { Image(#function) }
    static var ic16StopCircle: Image { Image(#function) }
    static var ic16Sun: Image { Image(#function) }
    static var ic16Sunrise: Image { Image(#function) }
    static var ic16Sunset: Image { Image(#function) }
    static var ic16Support: Image { Image(#function) }
    static var ic16Tablet: Image { Image(#function) }
    static var ic16Tag: Image { Image(#function) }
    static var ic16Target: Image { Image(#function) }
    static var ic16Tax: Image { Image(#function) }
    static var ic16Terminal: Image { Image(#function) }
    static var ic16Thermometer: Image { Image(#function) }
    static var ic16ThumbsDown: Image { Image(#function) }
    static var ic16ThumbsUp: Image { Image(#function) }
    static var ic16ToggleLeft: Image { Image(#function) }
    static var ic16ToggleRight: Image { Image(#function) }
    static var ic16Tool: Image { Image(#function) }
    static var ic16Train: Image { Image(#function) }
    static var ic16Transfer: Image { Image(#function) }
    static var ic16Trash: Image { Image(#function) }
    static var ic16Trash2: Image { Image(#function) }
    static var ic16Trello: Image { Image(#function) }
    static var ic16TrendingDown: Image { Image(#function) }
    static var ic16TrendingUp: Image { Image(#function) }
    static var ic16Triangle: Image { Image(#function) }
    static var ic16Truck: Image { Image(#function) }
    static var ic16Tv: Image { Image(#function) }
    static var ic16Twitch: Image { Image(#function) }
    static var ic16Twitter: Image { Image(#function) }
    static var ic16Type: Image { Image(#function) }
    static var ic16Umbrella: Image { Image(#function) }
    static var ic16Underline: Image { Image(#function) }
    static var ic16Unlock: Image { Image(#function) }
    static var ic16Upload: Image { Image(#function) }
    static var ic16UploadCloud: Image { Image(#function) }
    static var ic16User: Image { Image(#function) }
    static var ic16UserCheck: Image { Image(#function) }
    static var ic16UserMinus: Image { Image(#function) }
    static var ic16UserPlus: Image { Image(#function) }
    static var ic16UserX: Image { Image(#function) }
    static var ic16Users: Image { Image(#function) }
    static var ic16Video: Image { Image(#function) }
    static var ic16VideoOff: Image { Image(#function) }
    static var ic16Voicemail: Image { Image(#function) }
    static var ic16Volume: Image { Image(#function) }
    static var ic16Volume1: Image { Image(#function) }
    static var ic16Volume2: Image { Image(#function) }
    static var ic16VolumeX: Image { Image(#function) }
    static var ic16Waiting: Image { Image(#function) }
    static var ic16Watch: Image { Image(#function) }
    static var ic16WheelOfFortune: Image { Image(#function) }
    static var ic16Wifi: Image { Image(#function) }
    static var ic16WifiOff: Image { Image(#function) }
    static var ic16Wind: Image { Image(#function) }
    static var ic16XCircle: Image { Image(#function) }
    static var ic16XOctagon: Image { Image(#function) }
    static var ic16XSquare: Image { Image(#function) }
    static var ic16Youtube: Image { Image(#function) }
    static var ic16Zap: Image { Image(#function) }
    static var ic16ZapOff: Image { Image(#function) }
    static var ic16ZoomIn: Image { Image(#function) }
    static var ic16ZoomOut: Image { Image(#function) }
    static var ic18Check: Image { Image(#function) }
    static var ic20ForaNy: Image { Image(#function) }
    static var ic24Ball: Image { Image(#function) }
    static var ic2412Circle: Image { Image(#function) }
    static var ic24Apple: Image { Image(#function) }
    static var ic24Tariff: Image { Image(#function) }
    static var ic24Abroad: Image { Image(#function) }
    static var ic24AbroadLine: Image { Image(#function) }
    static var ic24Account1: Image { Image(#function) }
    static var ic24ActivatedCreditCard: Image { Image(#function) }
    static var ic24Activity: Image { Image(#function) }
    static var ic24Airplay: Image { Image(#function) }
    static var ic24AlertCircle: Image { Image(#function) }
    static var ic24AlertOctagon: Image { Image(#function) }
    static var ic24AlertTriangle: Image { Image(#function) }
    static var ic24AlignCenter: Image { Image(#function) }
    static var ic24AlignJustify: Image { Image(#function) }
    static var ic24AlignLeft: Image { Image(#function) }
    static var ic24AlignRight: Image { Image(#function) }
    static var ic24AllProucts: Image { Image(#function) }
    static var ic24Anchor: Image { Image(#function) }
    static var ic24Aperture: Image { Image(#function) }
    static var ic24Archive: Image { Image(#function) }
    static var ic24ArrowDown: Image { Image(#function) }
    static var ic24ArrowDownCircle: Image { Image(#function) }
    static var ic24ArrowDownLeft: Image { Image(#function) }
    static var ic24ArrowDownLine: Image { Image(#function) }
    static var ic24ArrowDownRight: Image { Image(#function) }
    static var ic24ArrowLeft: Image { Image(#function) }
    static var ic24ArrowLeftCircle: Image { Image(#function) }
    static var ic24ArrowRight: Image { Image(#function) }
    static var ic24ArrowRightCircle: Image { Image(#function) }
    static var ic24ArrowUp: Image { Image(#function) }
    static var ic24ArrowUpCircle: Image { Image(#function) }
    static var ic24ArrowUpLeft: Image { Image(#function) }
    static var ic24ArrowUpRight: Image { Image(#function) }
    static var ic24AtSign: Image { Image(#function) }
    static var ic24Award: Image { Image(#function) }
    static var ic24Bank: Image { Image(#function) }
    static var ic24BarChart: Image { Image(#function) }
    static var ic24BarChart2: Image { Image(#function) }
    static var ic24BarInOrder: Image { Image(#function) }
    static var ic24BarcodeScanner2: Image { Image(#function) }
    static var ic24Battery: Image { Image(#function) }
    static var ic24BatteryCharging: Image { Image(#function) }
    static var ic24Bell: Image { Image(#function) }
    static var ic24BellOff: Image { Image(#function) }
    static var ic24Between: Image { Image(#function) }
    static var ic24BirthdayCake: Image { Image(#function) }
    static var ic24Bluetooth: Image { Image(#function) }
    static var ic24Bold: Image { Image(#function) }
    static var ic24Book: Image { Image(#function) }
    static var ic24BookOpen: Image { Image(#function) }
    static var ic24Bookmark: Image { Image(#function) }
    static var ic24Box: Image { Image(#function) }
    static var ic24Briefcase: Image { Image(#function) }
    static var ic24Bulb: Image { Image(#function) }
    static var ic24Businessman: Image { Image(#function) }
    static var ic24Cafe: Image { Image(#function) }
    static var ic24Calendar: Image { Image(#function) }
    static var ic24CalendarPayment: Image { Image(#function) }
    static var ic24Camera: Image { Image(#function) }
    static var ic24CameraOff: Image { Image(#function) }
    static var ic24Car: Image { Image(#function) }
    static var ic24Cash: Image { Image(#function) }
    static var ic24Cashback: Image { Image(#function) }
    static var ic24Cashterminal: Image { Image(#function) }
    static var ic24Cast: Image { Image(#function) }
    static var ic24Catering: Image { Image(#function) }
    static var ic24ChatActive: Image { Image(#function) }
    static var ic24ChatInactive: Image { Image(#function) }
    static var ic24Check: Image { Image(#function) }
    static var ic24CheckCircle: Image { Image(#function) }
    static var ic24CheckSquare: Image { Image(#function) }
    static var ic24ChevronDown: Image { Image(#function) }
    static var ic24ChevronLeft: Image { Image(#function) }
    static var ic24ChevronRight: Image { Image(#function) }
    static var ic24ChevronUp: Image { Image(#function) }
    static var ic24ChevronsDown: Image { Image(#function) }
    static var ic24ChevronsLeft: Image { Image(#function) }
    static var ic24ChevronsRight: Image { Image(#function) }
    static var ic24ChevronsUp: Image { Image(#function) }
    static var ic24Chrome: Image { Image(#function) }
    static var ic24Circle: Image { Image(#function) }
    static var ic24CircleClose: Image { Image(#function) }
    static var ic24CircleRefresh: Image { Image(#function) }
    static var ic24Clipboard: Image { Image(#function) }
    static var ic24Clock: Image { Image(#function) }
    static var ic24Close: Image { Image(#function) }
    static var ic24Clothes: Image { Image(#function) }
    static var ic24Cloud: Image { Image(#function) }
    static var ic24CloudDrizzle: Image { Image(#function) }
    static var ic24CloudLightning: Image { Image(#function) }
    static var ic24CloudOff: Image { Image(#function) }
    static var ic24CloudRain: Image { Image(#function) }
    static var ic24CloudSnow: Image { Image(#function) }
    static var ic24Code: Image { Image(#function) }
    static var ic24Codepen: Image { Image(#function) }
    static var ic24Codesandbox: Image { Image(#function) }
    static var ic24Coffee: Image { Image(#function) }
    static var ic24Coins: Image { Image(#function) }
    static var ic24Columns: Image { Image(#function) }
    static var ic24Command: Image { Image(#function) }
    static var ic24Compass: Image { Image(#function) }
    static var ic24Contract: Image { Image(#function) }
    static var ic24Copy: Image { Image(#function) }
    static var ic24CornerDownLeft: Image { Image(#function) }
    static var ic24CornerDownRight: Image { Image(#function) }
    static var ic24CornerLeftDown: Image { Image(#function) }
    static var ic24CornerLeftUp: Image { Image(#function) }
    static var ic24CornerRightDown: Image { Image(#function) }
    static var ic24CornerRightUp: Image { Image(#function) }
    static var ic24CornerUpLeft: Image { Image(#function) }
    static var ic24CornerUpRight: Image { Image(#function) }
    static var ic24Cpu: Image { Image(#function) }
    static var ic24CreditCard: Image { Image(#function) }
    static var ic24CreditCardValidity: Image { Image(#function) }
    static var ic24CreditColor: Image { Image(#function) }
    static var ic24Crop: Image { Image(#function) }
    static var ic24Crosshair: Image { Image(#function) }
    static var ic24Crosshair1: Image { Image(#function) }
    static var ic24CurrencyExchange: Image { Image(#function) }
    static var ic24Customer: Image { Image(#function) }
    static var ic24Database: Image { Image(#function) }
    static var ic24DeactivatedCreditCard: Image { Image(#function) }
    static var ic24Delete: Image { Image(#function) }
    static var ic24Department: Image { Image(#function) }
    static var ic24DepositPlusColor: Image { Image(#function) }
    static var ic24Disc: Image { Image(#function) }
    static var ic24Divide: Image { Image(#function) }
    static var ic24DivideCircle: Image { Image(#function) }
    static var ic24DivideSquare: Image { Image(#function) }
    static var ic24DollarSign: Image { Image(#function) }
    static var ic24Donate: Image { Image(#function) }
    static var ic24Download: Image { Image(#function) }
    static var ic24DownloadCloud: Image { Image(#function) }
    static var ic24Dribbble: Image { Image(#function) }
    static var ic24DriversLicense: Image { Image(#function) }
    static var ic24Droplet: Image { Image(#function) }
    static var ic24EWallet: Image { Image(#function) }
    static var ic24Edit: Image { Image(#function) }
    static var ic24Edit2: Image { Image(#function) }
    static var ic24Edit3: Image { Image(#function) }
    static var ic24Education: Image { Image(#function) }
    static var ic24Egrn: Image { Image(#function) }
    static var ic24Emblem: Image { Image(#function) }
    static var ic24ExternalLink: Image { Image(#function) }
    static var ic24Eye: Image { Image(#function) }
    static var ic24EyeOff: Image { Image(#function) }
    static var ic24FaceId: Image { Image(#function) }
    static var ic24FacebK: Image { Image(#function) }
    static var ic24FastForward: Image { Image(#function) }
    static var ic24Favorites: Image { Image(#function) }
    static var ic24Feather: Image { Image(#function) }
    static var ic24Female: Image { Image(#function) }
    static var ic24Fence: Image { Image(#function) }
    static var ic24Figma: Image { Image(#function) }
    static var ic24File: Image { Image(#function) }
    static var ic24FileHash: Image { Image(#function) }
    static var ic24FileMinus: Image { Image(#function) }
    static var ic24FilePlus: Image { Image(#function) }
    static var ic24FileText: Image { Image(#function) }
    static var ic24FilePluseColor: Image { Image(#function) }
    static var ic24Film: Image { Image(#function) }
    static var ic24Filter: Image { Image(#function) }
    static var ic24FireColor: Image { Image(#function) }
    static var ic24Fish: Image { Image(#function) }
    static var ic24Flag: Image { Image(#function) }
    static var ic24Folder: Image { Image(#function) }
    static var ic24FolderMinus: Image { Image(#function) }
    static var ic24FolderPlus: Image { Image(#function) }
    static var ic24Framer: Image { Image(#function) }
    static var ic24Frown: Image { Image(#function) }
    static var ic24Gamepad: Image { Image(#function) }
    static var ic24Gift: Image { Image(#function) }
    static var ic24GitBranch: Image { Image(#function) }
    static var ic24GitCommit: Image { Image(#function) }
    static var ic24GitMerge: Image { Image(#function) }
    static var ic24GitPullRequest: Image { Image(#function) }
    static var ic24Github: Image { Image(#function) }
    static var ic24Gitlab: Image { Image(#function) }
    static var ic24Globe: Image { Image(#function) }
    static var ic24Grid: Image { Image(#function) }
    static var ic24Hammer: Image { Image(#function) }
    static var ic24HardDrive: Image { Image(#function) }
    static var ic24Hash: Image { Image(#function) }
    static var ic24Headphones: Image { Image(#function) }
    static var ic24Heart: Image { Image(#function) }
    static var ic24HelpCircle: Image { Image(#function) }
    static var ic24Hexagon: Image { Image(#function) }
    static var ic24HistoryActive: Image { Image(#function) }
    static var ic24HistoryInactive: Image { Image(#function) }
    static var ic24Holiday: Image { Image(#function) }
    static var ic24Home: Image { Image(#function) }
    static var ic24Ic24Heartbeat: Image { Image(#function) }
    static var ic24IconMessage: Image { Image(#function) }
    static var ic24Image: Image { Image(#function) }
    static var ic24Inbox: Image { Image(#function) }
    static var ic24Info: Image { Image(#function) }
    static var ic24Instagram: Image { Image(#function) }
    static var ic24InsuranceColor: Image { Image(#function) }
    static var ic24InternationalPassport: Image { Image(#function) }
    static var ic24Italic: Image { Image(#function) }
    static var ic24Key: Image { Image(#function) }
    static var ic24Keyboard: Image { Image(#function) }
    static var ic24Kids: Image { Image(#function) }
    static var ic24Layers: Image { Image(#function) }
    static var ic24Layout: Image { Image(#function) }
    static var ic24LifeBuoy: Image { Image(#function) }
    static var ic24Limits: Image { Image(#function) }
    static var ic24Link: Image { Image(#function) }
    static var ic24Link2: Image { Image(#function) }
    static var ic24Linkedin: Image { Image(#function) }
    static var ic24List: Image { Image(#function) }
    static var ic24Loader: Image { Image(#function) }
    static var ic24Location: Image { Image(#function) }
    static var ic24Lock: Image { Image(#function) }
    static var ic24LogIn: Image { Image(#function) }
    static var ic24LogOut: Image { Image(#function) }
    static var ic24LogoForaColor: Image { Image(#function) }
    static var ic24LogoForaLine: Image { Image(#function) }
    static var ic24LogoForaWhiteElipse: Image { Image(#function) }
    static var ic24LogoForaOneColor: Image { Image(#function) }
    static var ic24Mail: Image { Image(#function) }
    static var ic24Male: Image { Image(#function) }
    static var ic24Map: Image { Image(#function) }
    static var ic24MapPin: Image { Image(#function) }
    static var ic24MathMinus: Image { Image(#function) }
    static var ic24MathPlus: Image { Image(#function) }
    static var ic24Maximize: Image { Image(#function) }
    static var ic24MaximizeArrow: Image { Image(#function) }
    static var ic24MaximizeSquare: Image { Image(#function) }
    static var ic24Meh: Image { Image(#function) }
    static var ic24Menu: Image { Image(#function) }
    static var ic24MessageCircle: Image { Image(#function) }
    static var ic24MessageSquare: Image { Image(#function) }
    static var ic24MessageSquareNumber: Image { Image(#function) }
    static var ic24Metro: Image { Image(#function) }
    static var ic24Mic: Image { Image(#function) }
    static var ic24MicOff: Image { Image(#function) }
    static var ic24Minimize: Image { Image(#function) }
    static var ic24Minimize2: Image { Image(#function) }
    static var ic24MinusCircle: Image { Image(#function) }
    static var ic24MinusSquare: Image { Image(#function) }
    static var ic24MinusSquares: Image { Image(#function) }
    static var ic24Mlm: Image { Image(#function) }
    static var ic24Monitor: Image { Image(#function) }
    static var ic24Moon: Image { Image(#function) }
    static var ic24MoreHorizontal: Image { Image(#function) }
    static var ic24MoreHorizontalColor: Image { Image(#function) }
    static var ic24MoreVertical: Image { Image(#function) }
    static var ic24Mortgage: Image { Image(#function) }
    static var ic24MousePointer: Image { Image(#function) }
    static var ic24Move: Image { Image(#function) }
    static var ic24Music: Image { Image(#function) }
    static var ic24Navigation: Image { Image(#function) }
    static var ic24NewCard: Image { Image(#function) }
    static var ic24NewCardColor: Image { Image(#function) }
    static var ic24Nfc: Image { Image(#function) }
    static var ic24Octagon: Image { Image(#function) }
    static var ic24OtherCard: Image { Image(#function) }
    static var ic24Package: Image { Image(#function) }
    static var ic24Paperclip: Image { Image(#function) }
    static var ic24Pass: Image { Image(#function) }
    static var ic24Passport: Image { Image(#function) }
    static var ic24Pause: Image { Image(#function) }
    static var ic24PauseCircle: Image { Image(#function) }
    static var ic24PaymentMethod: Image { Image(#function) }
    static var ic24PaymentsActive: Image { Image(#function) }
    static var ic24PaymentsInactive: Image { Image(#function) }
    static var ic24PenTool: Image { Image(#function) }
    static var ic24Percent: Image { Image(#function) }
    static var ic24PercentCommission: Image { Image(#function) }
    static var ic24Permissions: Image { Image(#function) }
    static var ic24Phone: Image { Image(#function) }
    static var ic24PhoneCall: Image { Image(#function) }
    static var ic24PhoneForwarded: Image { Image(#function) }
    static var ic24PhoneIncoming: Image { Image(#function) }
    static var ic24PhoneMissed: Image { Image(#function) }
    static var ic24PhoneOff: Image { Image(#function) }
    static var ic24PhoneOutgoing: Image { Image(#function) }
    static var ic24PieChart: Image { Image(#function) }
    static var ic24Pincode: Image { Image(#function) }
    static var ic24Plane: Image { Image(#function) }
    static var ic24Play: Image { Image(#function) }
    static var ic24PlayCircle: Image { Image(#function) }
    static var ic24Plus: Image { Image(#function) }
    static var ic24PlusCircle: Image { Image(#function) }
    static var ic24PlusSquare: Image { Image(#function) }
    static var ic24PlusSquares: Image { Image(#function) }
    static var ic24Pocket: Image { Image(#function) }
    static var ic24PosteRestante: Image { Image(#function) }
    static var ic24Power: Image { Image(#function) }
    static var ic24Printer: Image { Image(#function) }
    static var ic24Promotions: Image { Image(#function) }
    static var ic24Rabbit: Image { Image(#function) }
    static var ic24Radio: Image { Image(#function) }
    static var ic24RadioChecked: Image { Image(#function) }
    static var ic24RadioDefolt: Image { Image(#function) }
    static var ic24RefreshCcw: Image { Image(#function) }
    static var ic24RefreshCw: Image { Image(#function) }
    static var ic24RegistrationAllday: Image { Image(#function) }
    static var ic24RegistrationPercent: Image { Image(#function) }
    static var ic24RegistrationPhone: Image { Image(#function) }
    static var ic24RegistrationTime: Image { Image(#function) }
    static var ic24Repeat: Image { Image(#function) }
    static var ic24Requisites: Image { Image(#function) }
    static var ic24Rescheduling: Image { Image(#function) }
    static var ic24ResendCard: Image { Image(#function) }
    static var ic24Rewind: Image { Image(#function) }
    static var ic24Roller: Image { Image(#function) }
    static var ic24RotateCcw: Image { Image(#function) }
    static var ic24RotateCw: Image { Image(#function) }
    static var ic24Rss: Image { Image(#function) }
    static var ic24Save: Image { Image(#function) }
    static var ic24Sbp: Image { Image(#function) }
    static var ic24SbpLine: Image { Image(#function) }
    static var ic24Scissors: Image { Image(#function) }
    static var ic24Search: Image { Image(#function) }
    static var ic24Send: Image { Image(#function) }
    static var ic24Server: Image { Image(#function) }
    static var ic24Settings: Image { Image(#function) }
    static var ic24Share: Image { Image(#function) }
    static var ic24Share2: Image { Image(#function) }
    static var ic24Shield: Image { Image(#function) }
    static var ic24ShieldOff: Image { Image(#function) }
    static var ic24ShoppingBag: Image { Image(#function) }
    static var ic24ShoppingCart: Image { Image(#function) }
    static var ic24Shuffle: Image { Image(#function) }
    static var ic24Sidebar: Image { Image(#function) }
    static var ic24SkanCard: Image { Image(#function) }
    static var ic24SkipBack: Image { Image(#function) }
    static var ic24SkipForward: Image { Image(#function) }
    static var ic24Slack: Image { Image(#function) }
    static var ic24Slash: Image { Image(#function) }
    static var ic24Sliders: Image { Image(#function) }
    static var ic24Smartphone: Image { Image(#function) }
    static var ic24Smile: Image { Image(#function) }
    static var ic24SmsColor: Image { Image(#function) }
    static var ic24SmsCode: Image { Image(#function) }
    static var ic24Speaker: Image { Image(#function) }
    static var ic24Square: Image { Image(#function) }
    static var ic24Star: Image { Image(#function) }
    static var ic24Sticker: Image { Image(#function) }
    static var ic24StopCircle: Image { Image(#function) }
    static var ic24Sts: Image { Image(#function) }
    static var ic24SubscrOn: Image { Image(#function) }
    static var ic24SubscrOnColor: Image { Image(#function) }
    static var ic24Subscriptions: Image { Image(#function) }
    static var ic24Sun: Image { Image(#function) }
    static var ic24Sunrise: Image { Image(#function) }
    static var ic24Sunset: Image { Image(#function) }
    static var ic24Support: Image { Image(#function) }
    static var ic24Tablet: Image { Image(#function) }
    static var ic24Tag: Image { Image(#function) }
    static var ic24Target: Image { Image(#function) }
    static var ic24Tax: Image { Image(#function) }
    static var ic24Telegram: Image { Image(#function) }
    static var ic24Terminal: Image { Image(#function) }
    static var ic24Thermometer: Image { Image(#function) }
    static var ic24ThumbsDown: Image { Image(#function) }
    static var ic24ThumbsUp: Image { Image(#function) }
    static var ic24ToggleLeft: Image { Image(#function) }
    static var ic24ToggleRight: Image { Image(#function) }
    static var ic24Tool: Image { Image(#function) }
    static var ic24Train: Image { Image(#function) }
    static var ic24Transfer: Image { Image(#function) }
    static var ic24Trash: Image { Image(#function) }
    static var ic24Trash2: Image { Image(#function) }
    static var ic24Trello: Image { Image(#function) }
    static var ic24TrendingDown: Image { Image(#function) }
    static var ic24TrendingUp: Image { Image(#function) }
    static var ic24Triangle: Image { Image(#function) }
    static var ic24Truck: Image { Image(#function) }
    static var ic24Tv: Image { Image(#function) }
    static var ic24Twitch: Image { Image(#function) }
    static var ic24Twitter: Image { Image(#function) }
    static var ic24Type: Image { Image(#function) }
    static var ic24Umbrella: Image { Image(#function) }
    static var ic24Underline: Image { Image(#function) }
    static var ic24Unlock: Image { Image(#function) }
    static var ic24Upload: Image { Image(#function) }
    static var ic24UploadCloud: Image { Image(#function) }
    static var ic24User: Image { Image(#function) }
    static var ic24UserCheck: Image { Image(#function) }
    static var ic24UserMinus: Image { Image(#function) }
    static var ic24UserPlus: Image { Image(#function) }
    static var ic24UserX: Image { Image(#function) }
    static var ic24Users: Image { Image(#function) }
    static var ic24Viber: Image { Image(#function) }
    static var ic24Video: Image { Image(#function) }
    static var ic24VideoOff: Image { Image(#function) }
    static var ic24Visa: Image { Image(#function) }
    static var ic24Voicemail: Image { Image(#function) }
    static var ic24Volume: Image { Image(#function) }
    static var ic24Volume1: Image { Image(#function) }
    static var ic24Volume2: Image { Image(#function) }
    static var ic24VolumeX: Image { Image(#function) }
    static var ic24Wallet: Image { Image(#function) }
    static var ic24Watch: Image { Image(#function) }
    static var ic24Water: Image { Image(#function) }
    static var ic24Whatsapp: Image { Image(#function) }
    static var ic24WheelOfFortune: Image { Image(#function) }
    static var ic24Wifi: Image { Image(#function) }
    static var ic24WifiOff: Image { Image(#function) }
    static var ic24Wind: Image { Image(#function) }
    static var ic24XCircle: Image { Image(#function) }
    static var ic24XOctagon: Image { Image(#function) }
    static var ic24XSquare: Image { Image(#function) }
    static var ic24Youtube: Image { Image(#function) }
    static var ic24Zap: Image { Image(#function) }
    static var ic24ZapOff: Image { Image(#function) }
    static var ic24Zkx: Image { Image(#function) }
    static var ic24ZoomIn: Image { Image(#function) }
    static var ic24ZoomOut: Image { Image(#function) }
    static var ic32AbroadLine: Image { Image(#function) }
    static var ic32Camera: Image { Image(#function) }
    static var ic32Edit2: Image { Image(#function) }
    static var ic32Emblem: Image { Image(#function) }
    static var ic32Globe: Image { Image(#function) }
    static var ic32Image: Image { Image(#function) }
    static var ic32Location: Image { Image(#function) }
    static var ic32LogoForaLine: Image { Image(#function) }
    static var ic32Office: Image { Image(#function) }
    static var ic32Rectangle: Image { Image(#function) }
    static var ic32Sbp: Image { Image(#function) }
    static var ic32SbpLine: Image { Image(#function) }
    static var ic32Search: Image { Image(#function) }
    static var ic32Service: Image { Image(#function) }
    static var ic32Swap: Image { Image(#function) }
    static var ic32Trash: Image { Image(#function) }
    static var ic32UserCheck: Image { Image(#function) }
    static var ic32UserPlus: Image { Image(#function) }
    static var ic40Qr: Image { Image(#function) }
    static var ic40TvInternet: Image { Image(#function) }
    static var ic40ZkxServices: Image { Image(#function) }
    static var ic40AirTickets: Image { Image(#function) }
    static var ic40ArrowRightCircle: Image { Image(#function) }
    static var ic40BankServices: Image { Image(#function) }
    static var ic40Beauty: Image { Image(#function) }
    static var ic40Card: Image { Image(#function) }
    static var ic40Catering: Image { Image(#function) }
    static var ic40ClothesAccessories: Image { Image(#function) }
    static var ic40Danger: Image { Image(#function) }
    static var ic40Delete: Image { Image(#function) }
    static var ic40Educations: Image { Image(#function) }
    static var ic40Entertainment: Image { Image(#function) }
    static var ic40FaceId: Image { Image(#function) }
    static var ic40FinancialRiskInsurance: Image { Image(#function) }
    static var ic40Goods: Image { Image(#function) }
    static var ic40GovernmentServices: Image { Image(#function) }
    static var ic40Helth: Image { Image(#function) }
    static var ic40Lock: Image { Image(#function) }
    static var ic40Multimedia: Image { Image(#function) }
    static var ic40Passport: Image { Image(#function) }
    static var ic40PropertyInsurance: Image { Image(#function) }
    static var ic40Recreation: Image { Image(#function) }
    static var ic40Renovation: Image { Image(#function) }
    static var ic40Restaurant: Image { Image(#function) }
    static var ic40Sbp: Image { Image(#function) }
    static var ic40Services: Image { Image(#function) }
    static var ic40ShoppingOther: Image { Image(#function) }
    static var ic40Smth: Image { Image(#function) }
    static var ic40Star: Image { Image(#function) }
    static var ic40Supermarket: Image { Image(#function) }
    static var ic40Telephone: Image { Image(#function) }
    static var ic40TouchId: Image { Image(#function) }
    static var ic40TrainTicket: Image { Image(#function) }
    static var ic40Transport: Image { Image(#function) }
    static var ic48Abroad: Image { Image(#function) }
    static var ic48AlertCircle: Image { Image(#function) }
    static var ic48AnotherCard: Image { Image(#function) }
    static var ic48BankDetails: Image { Image(#function) }
    static var ic48BarcodeScanner: Image { Image(#function) }
    static var ic48BetweenTheir: Image { Image(#function) }
    static var ic48Check: Image { Image(#function) }
    static var ic48Clock: Image { Image(#function) }
    static var ic48Close: Image { Image(#function) }
    static var ic48Credit: Image { Image(#function) }
    static var ic48Info: Image { Image(#function) }
    static var ic48PinAtm: Image { Image(#function) }
    static var ic48PinManyBranchesBlack: Image { Image(#function) }
    static var ic48PinManyBranchesRed: Image { Image(#function) }
    static var ic48PinOffice: Image { Image(#function) }
    static var ic48PinOthers: Image { Image(#function) }
    static var ic48PinTerminal: Image { Image(#function) }
    static var ic48Search: Image { Image(#function) }
    static var ic48Settings: Image { Image(#function) }
    static var ic48Telephone: Image { Image(#function) }
    static var ic48Tool: Image { Image(#function) }
    static var ic48UploadToAccount: Image { Image(#function) }
    static var ic48User: Image { Image(#function) }
    static var ic56Sbp: Image { Image(#function) }
    static var ic64TouchId: Image { Image(#function) }
    static var ic64FaceId: Image { Image(#function) }
    static var ic64ForaColor: Image { Image(#function) }
    static var ic64Goods: Image { Image(#function) }
    static var ic72Sbp: Image { Image(#function) }
    static var ic96Sbp: Image { Image(#function) }
}
