##########

stages:
  - test
  - build
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone
  GEM_HOME: .vendor/gem_install

before_script:
  - gem install bundler
  - bundle install

# start only on runner with label "macos"
default:
  tags:
    - macos

fastlane-test:
  stage: test
  when: manual
  only:
    - ci_setup
  script:
    - bundle exec fastlane test

fastlane-build-beta:
  stage: build
  when: manual
  allow_failure: false
  only:
    - ci_setup
  script:
    - bundle exec fastlane build production:false
  artifacts:
    paths:
      - ./fastlane/build/$APP_NAME.ipa
    expire_in: 1 week

fastlane-deploy:
  stage: deploy
  when: on_success
  only:
    - ci_setup
  script:
    - bundle exec fastlane deploy
