##########

stages:
  - test
  - build

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone
  GEM_HOME: .vendor/gem_install

# start only on runner with label "macos"
default:
  tags:
    - macos

fastlane-test:
  stage: test
#  when: manual
  only:
    - ci_setup
  script:
    - fastlane tests

build:
  stage: build
  only:
    - ci_setup
  script:
    - bundle install
    - bundle exec fastlane ForaBank
  artifacts:
    paths:
    - ./ForaBank.ipa

