# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|

    ENV["APPSTORE_API_KEY"] = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_KEY_ISSUER"],
      key_content: ENV["API_KEY_FILE"],
      is_key_content_base64: true,
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    if options[:production]
      ENV["XCODE_SCHEME"] = ENV["XCODE_SCHEME_RELEASE"]
    else
      ENV["XCODE_SCHEME"] = ENV["XCODE_SCHEME_BETA"]
    end

  end

  lane :test do

    run_tests(
      project: ENV["XCODE_PROJECT"],
      scheme: ENV["XCODE_SCHEME_TESTS"],
      devices: ["iPhone 12"],
      clean: false)

  end

  lane :build do |options|

    version = get_version_number(xcodeproj: ENV["XCODE_PROJECT"])
    build_number = latest_testflight_build_number(api_key: ENV["APPSTORE_API_KEY"], version: version) + 1
    increment_build_number(build_number: build_number, xcodeproj: ENV["XCODE_PROJECT"])

    build_app(scheme: ENV["XCODE_SCHEME"],
              project: ENV["XCODE_PROJECT"],
              output_directory: ENV["BUILD_PATH"],
              include_bitcode: true)
  end


  lane :deploy do |options|

    api_key = app_store_connect_api_key(
      key_id: "57LT9YX775",
      issuer_id: "69a6de8e-1f02-47e3-e053-5b8c7c11a4d1",
      key_filepath: "../auth/AuthKey_57LT9YX775.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(api_key: api_key, changelog: options[:changelog], ipa: "../build/ForaBank.ipa")

  end


  lane :build_deploy_beta do

    # last commit message
    last_commit_message = last_git_commit[:message]

    # increment build
    increment_build_number(xcodeproj: "ForaBank/ForaBank.xcodeproj")

    # commit & push
    version = get_version_number(xcodeproj: "ForaBank/ForaBank.xcodeproj") + " (" + get_build_number(xcodeproj: "ForaBank/ForaBank.xcodeproj") + ")"
    git_commit(path: ".", message: "Version " + version)
    push_to_git_remote

    # build
    build_beta

    # deploy
    deploy(changelog: last_commit_message)

  end

end
