# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|

  end

  lane :setup_beta do


  end

  lane :setup_release do


  end

  lane :tests do

    run_tests(
      project: ENV["XCODE_PROJECT"],
      scheme: ENV["XCODE_SCHEME_TESTS"],
      devices: ["iPhone 12"],
      clean: false)

  end

  lane :build_beta do

    build_app(scheme: "ForaBank-Deploy-Beta",
              project: "ForaBank/ForaBank.xcodeproj",
              output_directory: "../build",
              include_bitcode: true)
  end


  lane :deploy do |options|

    api_key = app_store_connect_api_key(
      key_id: "57LT9YX775",
      issuer_id: "69a6de8e-1f02-47e3-e053-5b8c7c11a4d1",
      key_filepath: "../auth/AuthKey_57LT9YX775.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(api_key: api_key, changelog: options[:changelog], ipa: "../build/ForaBank.ipa")

  end


  lane :build_deploy_beta do

    # last commit message
    last_commit_message = last_git_commit[:message]

    # increment build
    increment_build_number(xcodeproj: "ForaBank/ForaBank.xcodeproj")

    # commit & push
    version = get_version_number(xcodeproj: "ForaBank/ForaBank.xcodeproj") + " (" + get_build_number(xcodeproj: "ForaBank/ForaBank.xcodeproj") + ")"
    git_commit(path: ".", message: "Version " + version)
    push_to_git_remote

    # build
    build_beta

    # deploy
    deploy(changelog: last_commit_message)

  end

end
