# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :tests do

    run_tests(
      project: "ForaBank/ForaBank.xcodeproj",
      scheme: "ForaBank-Tests",
      devices: ["iPhone 12"],
      clean: false)

  end

  lane :build_beta do

    build_app(scheme: "ForaBank-Deploy-Beta",
              project: "ForaBank/ForaBank.xcodeproj",
              output_directory: "../build",
              include_bitcode: true)
  end

  lane :build_deploy_beta do

    # last commit message
    last_commit_message = last_git_commit[:message]

    # increment build
    increment_build_number(xcodeproj: "ForaBank/ForaBank.xcodeproj")

    # commit & push
    version = get_version_number(xcodeproj: "ForaBank/ForaBank.xcodeproj") + " (" + get_build_number(xcodeproj: "ForaBank/ForaBank.xcodeproj") + ")"
    git_commit(path: ".", message: "Version " + version)
    push_to_git_remote

    # build & sign
    build_beta

    # upload
    upload_to_testflight(api_key_path: "../auth/api_key_info.json", changelog: last_commit_message, ipa: "../build/ForaBank.ipa")

  end

end
